name: HeadLibrary
main: me.tigahz.headlibrary.HeadLibrary
description: Get heads from our library
author: Tigahz
version: 5.1.1
api-version: 1.13
commands:
  heads:
    aliases: [headlibrary, hl, skulls]
    description: Get heads