name: HeadLibrary
main: me.tigahz.headlibrary.HeadLibrary
description: Get heads from our library
author: Tigahz
version: 5.2
api-version: 1.13
softdepend:
  - Vault
commands:
  heads:
    aliases: [headlibrary, hl, skulls]
    description: Get heads